import { PrismaClient } from "@prisma/client";

const medicalSpecialties = [
  {
    name: "Family Medicine",
    description: "Focuses on providing comprehensive care to patients of all ages and genders. They handle a wide range of conditions, from routine checkups to chronic disease management.",
    medicalsubspeciality: [
      { name: "Geriatric Medicine", description: "Medical care for elderly patients, focusing on their unique health needs and age-related conditions." },
      { name: "Sports Medicine", description: "Medical care and treatment for athletes and sports-related injuries." },
      { name: "Palliative Medicine", description: "Specialty focused on improving quality of life for patients with serious illnesses." },
      { name: "Addiction Medicine", description: "Treatment and management of substance use disorders and addiction." },
      { name: "Adolescent Medicine", description: "Medical care for teenagers, focusing on their physical, emotional, and social well-being." },
      { name: "Hospice and Palliative Medicine", description: "Specialty focused on providing comfort and support to patients with serious illnesses and end-of-life care." },
      { name: "Sleep Medicine", description: "Diagnosis and treatment of sleep disorders." },
      { name: "Obesity Medicine", description: "Treatment and management of obesity through lifestyle modifications, medications, and surgical interventions." },
      { name: "Integrative Medicine", description: "Holistic approach combining conventional and alternative therapies to treat patients." },
      { name: "Preventive Medicine", description: "Specialty focused on promoting health, preventing disease, and managing public health programs." },
      { name: "Occupational Medicine", description: "Prevention and management of work-related injuries and illnesses." },
      { name: "Travel Medicine", description: "Specialty focused on health and safety during travel, including vaccinations and disease prevention." },
      { name: "Emergency Medicine", description: "Specialty focused on acute care of patients in emergency settings." },
      { name: "Rural Medicine", description: "Medical care provided in rural areas, often with limited resources and unique challenges." },
      { name: "Women's Health", description: "Medical specialty focused on the unique health needs of women throughout their lifespan." },
    ],
  },
  {
    name: "Internal Medicine",
    description: "Deals with the diagnosis and treatment of adult medical conditions, excluding surgery. They often manage complex and chronic diseases.",
    medicalsubspeciality: [
      { name: "Cardiology", description: "Study and treatment of disorders of the heart and blood vessels." },
      { name: "Gastroenterology", description: "Study and treatment of disorders of the digestive system, including the stomach, intestines, and liver." },
      { name: "Endocrinology", description: "Study of hormones and their disorders." },
      { name: "Nephrology", description: "Study and treatment of kidney diseases and disorders." },
      { name: "Pulmonology", description: "Diagnosis and treatment of diseases related to the respiratory system." },
      { name: "Rheumatology", description: "Diagnosis and treatment of diseases affecting joints, muscles, and bones." },
      { name: "Hematology", description: "Study and treatment of blood disorders and diseases." },
      { name: "Infectious Diseases", description: "Diagnosis and treatment of infections caused by bacteria, viruses, fungi, and parasites." },
      { name: "Geriatrics", description: "Medical subspecialty focused on the care of elderly patients and age-related health issues." },
      { name: "Allergy and Immunology", description: "Diagnosis and treatment of allergies and immune system disorders." },
      { name: "Oncology", description: "Study and treatment of cancer." },
      { name: "Neurology", description: "Study and treatment of disorders of the nervous system, including the brain, spinal cord, and nerves." },
      { name: "Dermatology", description: "Diagnosis and treatment of skin disorders." },
      { name: "Psychiatry", description: "Diagnosis, treatment, and prevention of mental disorders." },
      { name: "Critical Care Medicine", description: "Intensive care for critically ill patients." },
    ],
  },
  {
    name: "Pediatrics",
    description: "Specializes in the care of children from birth to adolescence. They handle a variety of childhood illnesses and developmental issues.",
    medicalsubspeciality: [
      { name: "Neonatology", description: "Medical subspecialty focused on the care of newborn infants, especially those who are premature or ill." },
      { name: "Pediatric cardiology", description: "Heart care for children." },
      { name: "Pediatric gastroenterology", description: "Specializes in digestive disorders in children, including Crohn's disease, celiac disease, and chronic constipation." },
      { name: "Pediatric endocrinology", description: "Diagnosis and treatment of hormone-related disorders in children and adolescents." },
      { name: "Pediatric nephrology", description: "Medical specialty focused on kidney diseases in children." },
      { name: "Pediatric pulmonology", description: "Diagnosis and treatment of respiratory disorders in children." },
      { name: "Pediatric hematology/oncology", description: "Diagnosis and treatment of blood disorders and cancers in children." },
      { name: "Pediatric neurology", description: "Medical specialty focused on diagnosing and treating neurological disorders in children." },
      { name: "Pediatric rheumatology", description: "Diagnosis and treatment of rheumatic diseases in children." },
      { name: "Pediatric infectious diseases", description: "Diagnosis and treatment of infectious diseases in children." },
      { name: "Pediatric emergency medicine", description: "Specialized care for children in urgent medical situations, including trauma, illness, and emergencies." },
      { name: "Pediatric critical care medicine", description: "Specialty focused on the care of critically ill children." },
      { name: "Pediatric dermatology", description: "Diagnosis and treatment of skin conditions in children." },
      { name: "Pediatric ophthalmology", description: "Medical specialty focused on eye disorders and vision problems in children." },
      { name: "Pediatric otolaryngology (ENT)", description: "Diagnosis and treatment of ear, nose, and throat conditions in children." },
      { name: "Pediatric orthopedics", description: "Orthopedic care for children's bone and joint conditions." },
      { name: "Pediatric urology", description: "Surgical and non-surgical treatment of urological conditions in children." },
      { name: "Pediatric surgery", description: "Surgical care for infants, children, and adolescents." },
      { name: "Pediatric radiology", description: "Imaging techniques used to diagnose and treat diseases in children." },
      { name: "Pediatric anesthesiology", description: "Anesthesia for children during surgery and other medical procedures." },
    ],
  },
  {
    name: "Allergy and Immunology",
    description: "Diagnoses and treats allergies, asthma, and other immune system disorders.",
    medicalsubspeciality: [
      { name: "Pediatric Allergy and Immunology", description: "Diagnosis and treatment of allergies and immune system disorders in children." },
      { name: "Clinical Immunology", description: "Diagnosis and treatment of disorders related to the immune system." },
      { name: "Allergy and Immunology Research", description: "Study of immune system disorders and allergic reactions, and development of treatments and prevention strategies." },
      { name: "Occupational Allergy and Immunology", description: "Diagnosis and treatment of allergies and immune system disorders related to occupational exposures." },
      { name: "Food Allergy and Immunology", description: "Diagnosis and treatment of allergies and immune system disorders related to food." },
      { name: "Drug Allergy and Immunology", description: "Diagnosis and management of drug allergies and immune system disorders." },
      { name: "Asthma and Allergy", description: "Specializes in the diagnosis and treatment of asthma and allergies." },
      { name: "Immunodeficiency Disorders", description: "Diagnosis and treatment of disorders that weaken the immune system." },
      { name: "Allergy and Immunology Dermatology", description: "Allergy and Immunology: Diagnosis and treatment of allergies and immune system disorders." },
      { name: "Allergy and Immunology Ophthalmology.", description: "Diagnosis and treatment of eye conditions related to allergies and immune system disorders." },
    ],
  },
  {
    name: "Anesthesiology",
    description: "Provides pain relief and manages patients before, during, and after surgery.",
    medicalsubspeciality: [
      { name: "Pain Medicine", description: "Specialty focused on managing and treating pain through various methods." },
      { name: "Critical Care Medicine", description: "Intensive care for critically ill patients." },
      { name: "Pediatric Anesthesiology", description: "Anesthesia for children during surgery and other medical procedures." },
      { name: "Obstetric Anesthesiology", description: "Anesthesia care for pregnant women during labor, delivery, and cesarean section." },
      { name: "Cardiothoracic Anesthesiology", description: "Anesthesia for heart and lung surgeries." },
      { name: "Neuroanesthesiology", description: "Anesthesia for neurosurgical procedures and management of patients with neurological disorders." },
      { name: "Regional Anesthesiology", description: "Anesthesia focused on numbing specific regions of the body for surgery or pain management." },
      { name: "Ambulatory Anesthesiology", description: "Anesthesia provided for patients undergoing procedures outside of the operating room." },
      { name: "Transplant Anesthesiology", description: "Anesthesia for patients undergoing organ transplantation surgery." },
      { name: "Palliative Medicine", description: "Specialty focused on improving quality of life for patients with serious illnesses." },
    ],
  },
  {
    name: "Cardiology",
    description: "Focuses on the heart and cardiovascular system. They diagnose and treat heart disease, arrhythmias, and other cardiovascular conditions.",
    medicalsubspeciality: [
      { name: "Interventional Cardiology", description: "Minimally invasive procedures to diagnose and treat heart conditions using catheters and other specialized tools." },
      { name: "Electrophysiology", description: "Study and treatment of electrical activities of the heart." },
      { name: "Nuclear Cardiology", description: "Use of radioactive substances to diagnose and treat heart conditions." },
      { name: "Cardiovascular Imaging", description: "Use of imaging techniques to diagnose and monitor heart and blood vessel conditions." },
      { name: "Heart Failure and Transplant Cardiology", description: "Specializes in the management of heart failure and performing heart transplants." },
      { name: "Pediatric Cardiology", description: "Diagnosis and treatment of heart conditions in children." },
      { name: "Adult Congenital Heart Disease", description: "Specialty that focuses on the care of adults with congenital heart defects." },
      { name: "Cardiac Rehabilitation", description: "Exercise and lifestyle interventions for patients recovering from heart conditions." },
      { name: "Preventive Cardiology", description: "Preventing heart disease through lifestyle changes and medication." },
      { name: "Vascular Medicine", description: "Diagnosis and treatment of diseases affecting the blood vessels and circulatory system." },
    ],
  },
  {
    name: "Dermatology",
    description: "Deals with the diagnosis and treatment of skin, hair, nail, and mucous membrane conditions.",
    medicalsubspeciality: [
      { name: "Dermatopathology", description: "Study of skin diseases using microscopic examination of skin tissue samples." },
      { name: "Pediatric Dermatology", description: "Diagnosis and treatment of skin conditions in children." },
      { name: "Mohs Surgery", description: "Precise skin cancer removal with immediate microscopic examination for complete eradication." },
      { name: "Cosmetic Dermatology", description: "Medical specialty focused on improving the appearance of the skin, hair, and nails." },
      { name: "Dermatologic Oncology", description: "Diagnosis and treatment of skin cancers and other malignancies affecting the skin." },
      { name: "Dermatologic Surgery", description: "Surgical treatment of skin conditions and cosmetic procedures." },
      { name: "Dermatologic Immunology", description: "Study of skin diseases caused by immune system dysfunction." },
      { name: "Dermatologic Laser Surgery", description: "Use of lasers for skin conditions like acne scars, birthmarks, and tattoo removal." },
      { name: "Dermatologic Allergy", description: "Diagnosis and treatment of allergic reactions and conditions affecting the skin." },
      { name: "Dermatologic Infectious Diseases", description: "Diagnosis and treatment of infectious diseases affecting the skin." },
    ],
  },
  {
    name: "Emergency Medicine",
    description: "Provides immediate care for critically ill or injured patients in emergency room settings.",
    medicalsubspeciality: [
      { name: "Pediatric Emergency Medicine", description: "Specialized care for children in urgent medical situations." },
      { name: "Sports Medicine", description: "Medical care and treatment for athletes and sports-related injuries." },
      { name: "Critical Care Medicine", description: "Intensive care for critically ill patients." },
      { name: "Toxicology", description: "Study and treatment of the adverse effects of drugs, chemicals, and toxins on the body." },
      { name: "Disaster Medicine", description: "Emergency medical care during natural or man-made disasters." },
      { name: "Hyperbaric Medicine", description: "Treatment of medical conditions using high-pressure oxygen in a pressurized chamber." },
      { name: "Medical Toxicology", description: "Study and treatment of poisoning and toxic effects of drugs, chemicals, and other substances." },
      { name: "Wilderness Medicine", description: "Medical care in remote or austere environments, often involving outdoor activities and extreme conditions." },
      { name: "Emergency Medical Services", description: "Rapid response medical care for acute illnesses and injuries outside of a hospital setting." },
      { name: "Ultrasound in Emergency Medicine", description: "Use of ultrasound technology for diagnosing and treating emergency medical conditions." },
    ],
  },
  {
    name: "Gastroenterology",
    description: "Specializes in the digestive system and its disorders, including liver, pancreas, and intestines.",
    medicalsubspeciality: [
      { name: "Hepatology", description: "Study and treatment of liver diseases." },
      { name: "Endoscopy", description: "Minimally invasive procedure using a flexible tube with a camera to examine internal organs." },
      { name: "Gastrointestinal oncology", description: "Diagnosis and treatment of cancers in the digestive system, including the stomach, intestines, and liver." },
      { name: "Inflammatory bowel disease", description: "Gastroenterology subspecialty focused on diagnosing and treating chronic inflammation of the digestive tract." },
      { name: "Gastrointestinal motility disorders", description: "Diagnosis and treatment of disorders affecting movement of the digestive system." },
      { name: "Pancreatology", description: "Study and treatment of diseases related to the pancreas, such as pancreatitis and pancreatic cancer." },
      { name: "Esophageal disorders", description: "Gastroenterology focused on diagnosing and treating disorders of the esophagus." },
      { name: "Functional gastrointestinal disorders", description: "Diagnosing and treating disorders affecting the function of the gastrointestinal tract." },
      { name: "Pediatric gastroenterology", description: "Specializes in digestive disorders in children, including Crohn's disease, celiac disease, and chronic constipation." },
      { name: "Interventional gastroenterology", description: "Minimally invasive procedures for diagnosing and treating gastrointestinal conditions using endoscopic techniques." },
    ],
  },
  {
    name: "General Surgery",
    description: "Performs surgical procedures on various parts of the body.",
    medicalsubspeciality: [
      { name: "Cardiothoracic Surgery", description: "Surgical treatment of diseases affecting the heart, lungs, and other structures in the chest." },
      { name: "Colorectal Surgery", description: "Surgical treatment of diseases affecting the colon, rectum, and anus." },
      { name: "Endocrine Surgery", description: "Surgical treatment of disorders related to the endocrine system, including thyroid, parathyroid, and adrenal glands." },
      { name: "Gastrointestinal Surgery", description: "Surgical treatment of diseases and conditions affecting the digestive system." },
      { name: "Hepatobiliary Surgery", description: "Surgical treatment of liver, gallbladder, and bile duct diseases." },
      { name: "Neurosurgery", description: "Surgical treatment of disorders affecting the brain, spine, and nervous system." },
      { name: "Orthopedic Surgery", description: "Surgical treatment of musculoskeletal conditions, including bones, joints, ligaments, tendons, and muscles." },
      { name: "Pediatric Surgery", description: "Surgical treatment of infants, children, and adolescents with congenital and acquired conditions." },
      { name: "Plastic Surgery", description: "Surgical specialty focused on reconstructing and enhancing the appearance of the body." },
      { name: "Surgical Oncology", description: "Surgical treatment of cancer, including tumor removal and lymph node dissection." },
      { name: "Transplant Surgery", description: "Surgical procedure involving the transplantation of organs or tissues from one person to another." },
      { name: "Trauma Surgery", description: "Surgical treatment of injuries caused by accidents or violence." },
      { name: "Urology Surgery", description: "Surgical treatment of diseases and conditions affecting the urinary tract and male reproductive system." },
      { name: "Vascular Surgery", description: "Surgical treatment of diseases affecting blood vessels, excluding the heart and brain." },
    ],
  },
  {
    name: "Neurology",
    description: "Deals with the nervous system and its disorders, including the brain, spinal cord, and nerves.",
    medicalsubspeciality: [
      { name: "Clinical Neurophysiology", description: "Diagnosis and management of neurological disorders using electrophysiological and neuroimaging techniques." },
      { name: "Neuromuscular Medicine", description: "Diagnosis and treatment of disorders affecting the nerves and muscles." },
      { name: "Neurocritical Care", description: "Intensive care for patients with life-threatening neurological conditions." },
      { name: "Neuro-oncology", description: "Diagnosis and treatment of brain and spinal cord tumors." },
      { name: "Neuro-ophthalmology", description: "Study of visual problems related to the nervous system, including optic nerve disorders and visual field defects." },
      { name: "Neurorehabilitation", description: "Restoring function and quality of life for patients with neurological disorders through therapy and rehabilitation." },
      { name: "Pediatric Neurology", description: "Medical specialty focused on diagnosing and treating neurological disorders in children." },
      { name: "Sleep Medicine", description: "Diagnosis and treatment of sleep disorders." },
      { name: "Vascular Neurology", description: "Diagnosis and treatment of cerebrovascular diseases, including stroke and aneurysms." },
      { name: "Epilepsy", description: "Neurology subspecialty focused on diagnosis and treatment of epilepsy and other seizure disorders." },
    ],
  },
  {
    name: "Obstetrics and Gynecology (OB-GYN)",
    description: "Provides care for women's reproductive health, including pregnancy, childbirth, and gynecological conditions.",
    medicalsubspeciality: [
      { name: "Maternal-Fetal Medicine", description: "Specialty focused on high-risk pregnancies and fetal abnormalities." },
      { name: "Reproductive Endocrinology and Infertility", description: "Diagnosis and treatment of hormonal disorders and infertility in both men and women." },
      { name: "Gynecologic Oncology", description: "Diagnosis and treatment of cancers affecting the female reproductive system." },
      { name: "Urogynecology", description: "Surgical treatment of pelvic floor disorders in women." },
      { name: "Female Pelvic Medicine and Reconstructive Surgery", description: "Surgical treatment for pelvic floor disorders in women." },
      { name: "Family Planning", description: "Reproductive health and contraception services for individuals and couples." },
      { name: "Pediatric and Adolescent Gynecology", description: "Medical care for reproductive health issues in children and teenagers." },
      { name: "Minimally Invasive Gynecologic Surgery", description: "Surgical procedures for gynecologic conditions using small incisions and specialized instruments." },
      { name: "Obstetric Anesthesiology", description: "Anesthesia care for pregnant women during labor, delivery, and cesarean section." },
      { name: "Reproductive Genetics", description: "Genetic testing and counseling for individuals and couples with reproductive concerns." },
    ],
  },
  {
    name: "Ophthalmology",
    description: "Specializes in the eyes and vision care, including performing eye surgery.",
    medicalsubspeciality: [
      { name: "Cornea and External Disease", description: "Diagnosis and treatment of corneal and external eye conditions." },
      { name: "Glaucoma", description: "Ophthalmology subspecialty focused on diagnosing and treating glaucoma, a group of eye conditions causing optic nerve damage." },
      { name: "Retina and Vitreous", description: "Ophthalmology subspecialty focused on diseases of the retina and vitreous humor." },
      { name: "Pediatric Ophthalmology", description: "Medical specialty focused on eye disorders and vision problems in children." },
      { name: "Neuro-Ophthalmology", description: "Diagnosis and treatment of visual problems related to the nervous system." },
      { name: "Oculoplastics and Orbit Surgery", description: "Surgical treatment of eye and eyelid disorders, as well as orbital diseases." },
      { name: "Uveitis and Ocular Immunology", description: "Diagnosis and treatment of inflammation in the eye and immune-related eye diseases." },
      { name: "Ophthalmic Pathology", description: "Study of diseases and conditions affecting the eyes and surrounding structures." },
      { name: "Ophthalmic Oncology", description: "Diagnosis and treatment of eye tumors and cancers." },
      { name: "Refractive Surgery", description: "Corrective surgery to improve vision by reshaping the cornea or lens." },
      { name: "Ocular Genetics", description: "Study of genetic disorders affecting the eyes and vision." },
      { name: "Ocular Oncology", description: "Diagnosis and treatment of tumors in the eye and surrounding structures." },
      { name: "Ocular Inflammation and Immunology", description: "Study and treatment of inflammation and immune disorders affecting the eyes." },
      { name: "Ocular Surface and Dry Eye Disorders", description: "Diagnosis and treatment of conditions affecting the surface of the eye and dry eye symptoms." },
      { name: "Ocular Trauma and Emergency Ophthalmology", description: "Treatment of eye injuries and urgent eye conditions." },
    ],
  },
  {
    name: "Orthopedic Surgery",
    description: "Deals with the musculoskeletal system, including bones, joints, muscles, and tendons. They perform orthopedic surgery to treat injuries and conditions.",
    medicalsubspeciality: [
      { name: "Hand Surgery", description: "Surgical treatment of hand and upper extremity conditions, including trauma, nerve compression, and arthritis." },
      { name: "Spine Surgery", description: "Surgical treatment of conditions affecting the spine, including spinal deformities, injuries, and degenerative diseases." },
      { name: "Joint Replacement Surgery", description: "Surgical procedure to replace damaged joints with artificial implants for improved mobility and pain relief." },
      { name: "Sports Medicine", description: "Medical care and treatment for athletes and sports-related injuries." },
      { name: "Pediatric Orthopedics", description: "Orthopedic care for children's bone and joint conditions." },
      { name: "Orthopedic Trauma Surgery", description: "Surgical treatment of fractures and injuries to the musculoskeletal system." },
      { name: "Foot and Ankle Surgery", description: "Surgical treatment of conditions affecting the foot and ankle." },
      { name: "Orthopedic Oncology", description: "Diagnosis and treatment of bone and soft tissue tumors." },
      { name: "Orthopedic Rehabilitation", description: "Rehabilitation of musculoskeletal injuries and conditions to restore function and improve quality of life." },
      { name: "Orthopedic Oncology", description: "Diagnosis and treatment of bone and soft tissue tumors." },
    ],
  },
  {
    name: "Otolaryngology (ENT)",
    description: "Focuses on the ear, nose, throat, head, and neck. They diagnose and treat conditions in these areas, including allergies, sinus infections, and hearing loss.",
    medicalsubspeciality: [
      { name: "Head and Neck Surgery", description: "Surgical treatment of conditions affecting the head and neck region." },
      { name: "Rhinology (Nose and Sinus Disorders)", description: "Diagnosis and treatment of disorders related to the nose and sinuses." },
      { name: "Laryngology (Voice and Swallowing Disorders)", description: "Diagnosis and treatment of voice and swallowing disorders related to the larynx." },
      { name: "Otology/Neurotology (Ear and Hearing Disorders)", description: "Diagnosis and treatment of ear and hearing disorders, including balance and skull base surgery." },
      { name: "Pediatric Otolaryngology", description: "Medical specialty focused on ear, nose, and throat disorders in children." },
      { name: "Facial Plastic and Reconstructive Surgery", description: "Surgical specialty focused on cosmetic and reconstructive procedures for the face and neck." },
      { name: "Sleep Medicine", description: "Diagnosis and treatment of sleep disorders." },
      { name: "Allergy and Immunology", description: "Diagnosis and treatment of allergies and immune system disorders." },
      { name: "Audiology (Hearing and Balance Testing)", description: "Diagnosis and treatment of hearing and balance disorders through testing and rehabilitation." },
      { name: "Speech-Language Pathology.", description: "Diagnosis and treatment of communication and swallowing disorders." },
    ],
  },
  {
    name: "Pathology",
    description: "Examines tissues and cells to diagnose diseases.",
    medicalsubspeciality: [
      { name: "Anatomic Pathology", description: "Diagnosing diseases through examination of tissues and cells under a microscope." },
      { name: "Clinical Pathology", description: "Laboratory medicine focused on diagnosing diseases through analysis of bodily fluids and tissues." },
      { name: "Forensic Pathology", description: "Investigates cause of death through autopsies and examination of medical evidence for legal purposes." },
      { name: "Hematopathology", description: "Study of blood disorders and diseases, including cancers, through examination of blood and bone marrow samples." },
      { name: "Dermatopathology", description: "Study of skin diseases using microscopic examination of skin tissue samples." },
      { name: "Neuropathology", description: "Study of diseases of the nervous system, including the brain, spinal cord, and peripheral nerves." },
      { name: "Pediatric Pathology", description: "Study of diseases in children, including diagnosis and treatment." },
      { name: "Molecular Pathology", description: "Study of molecular changes in cells and tissues to diagnose and treat diseases." },
      { name: "Cytopathology", description: "Study of cells to diagnose diseases, often through examination of samples under a microscope." },
      { name: "Surgical Pathology", description: "Diagnosing diseases through examination of tissue samples obtained during surgery." },
      { name: "Renal Pathology", description: "Study of kidney diseases through examination of kidney tissue samples." },
      { name: "Gastrointestinal Pathology", description: "Study of diseases affecting the digestive system, including the esophagus, stomach, intestines, and liver." },
      { name: "Pulmonary Pathology", description: "Study of lung diseases and disorders, including cancer, infections, and respiratory conditions." },
      { name: "Breast Pathology", description: "Diagnosis and study of diseases affecting the breast tissue." },
      { name: "Gynecologic Pathology", description: "Study of diseases of the female reproductive system, including the ovaries, uterus, and cervix." },
    ],
  },

  {
    name: "Physical Medicine and Rehabilitation (PM&R)",
    description: "Helps patients regain function and improve their quality of life after injuries, illnesses, or disabilities.",
    medicalsubspeciality: [
      { name: "Pain Medicine", description: "Specialty focused on managing and treating pain through various methods." },
      { name: "Spinal Cord Injury Medicine", description: "Specializes in the diagnosis and treatment of spinal cord injuries and related conditions." },
      { name: "Sports Medicine", description: "Medical care and treatment for athletes and sports-related injuries." },
      { name: "Pediatric Rehabilitation Medicine", description: "Medical specialty focused on improving function and quality of life for children with disabilities." },
      { name: "Brain Injury Medicine", description: "Specializes in the diagnosis and treatment of patients with brain injuries." },
      { name: "Neuromuscular Medicine", description: "Diagnosis and treatment of disorders affecting the nerves and muscles." },
      { name: "Geriatric Rehabilitation Medicine", description: "Medical specialty focused on rehabilitating elderly patients to improve their functional abilities and quality of life." },
      { name: "Musculoskeletal Rehabilitation", description: "Rehabilitation of musculoskeletal conditions through physical therapy, exercise, and other non-surgical interventions." },
      { name: "Electrodiagnostic Medicine", description: "Diagnosing and treating nerve and muscle disorders using electrical tests." },
      { name: "Occupational Medicine (within PM&R)", description: "Preventing and managing work-related injuries and illnesses, promoting workplace health and safety." },
    ],
  },

  {
    name: "Psychiatry",
    description: "Deals with mental, emotional, and behavioral disorders.",
    medicalsubspeciality: [
      { name: "Child and Adolescent Psychiatry", description: "Diagnosis and treatment of mental health disorders in children and adolescents." },
      { name: "Geriatric Psychiatry", description: "Psychiatry focused on mental health issues in older adults." },
      { name: "Addiction Psychiatry", description: "Treatment and management of substance use disorders and other addictive behaviors." },
      { name: "Forensic Psychiatry", description: "Psychiatry focused on the intersection of mental health and the legal system." },
      { name: "Consultation-Liaison Psychiatry", description: "Psychiatry focused on treating patients with comorbid medical and psychiatric conditions." },
      { name: "Psychosomatic Medicine", description: "Integration of psychological and physical aspects of health and illness." },
      { name: "Neuropsychiatry", description: "Integration of neurology and psychiatry to diagnose and treat disorders affecting both the brain and mind." },
      { name: "Sleep Medicine", description: "Diagnosis and treatment of sleep disorders." },
      { name: "Emergency Psychiatry", description: "Psychiatric care for patients in acute mental health crises in emergency department settings." },
      { name: "Community Psychiatry", description: "Psychiatry focused on providing mental health care in community settings." },
      { name: "Psycho-oncology", description: "Psychological care for cancer patients and their families." },
      { name: "Military Psychiatry", description: "Psychiatry specialized in treating mental health issues in military personnel." },
      { name: "Reproductive Psychiatry", description: "Psychiatry focused on mental health issues related to reproductive health and fertility." },
      { name: "Psychopharmacology", description: "Study of how drugs affect mental disorders and behavior." },
      { name: "Eating Disorders Psychiatry", description: "Diagnosis and treatment of mental health conditions related to disordered eating behaviors." },
    ],
  },

  {
    name: "Radiation Oncology",
    description: "Uses radiation to treat cancer and other diseases.",
    medicalsubspeciality: [
      { name: "Pediatric Radiation Oncology", description: "Treatment of cancer in children using radiation therapy." },
      { name: "Gynecologic Radiation Oncology", description: "Radiation treatment for gynecologic cancers, such as cervical, ovarian, and uterine cancer." },
      { name: "Head and Neck Radiation Oncology", description: "Treatment of head and neck cancers using radiation therapy." },
      { name: "Breast Radiation Oncology", description: "Radiation treatment for breast cancer." },
      { name: "Thoracic Radiation Oncology", description: "Treatment of cancer in the chest using radiation therapy." },
      { name: "Gastrointestinal Radiation Oncology", description: "Treatment of gastrointestinal cancers using radiation therapy." },
      { name: "Genitourinary Radiation Oncology", description: "Radiation treatment for cancers of the genitourinary system, including prostate, bladder, and kidney cancers." },
      { name: "Musculoskeletal Radiation Oncology", description: "Radiation therapy for bone and soft tissue tumors." },
      { name: "Central Nervous System Radiation Oncology", description: "Treatment of brain and spinal cord tumors using radiation therapy." },
      { name: "Skin Radiation Oncology", description: "Treatment of skin cancer using radiation therapy." },
    ],
  },

  {
    name: "Urology",
    description: "Focuses on the urinary tract and male reproductive system. They diagnose and treat conditions in these areas, including urinary incontinence, prostate cancer, and kidney stones.",
    medicalsubspeciality: [
      { name: "Pediatric Urology", description: "Surgical care for urological conditions in children." },
      { name: "Female Urology", description: "Urological care specifically focused on female reproductive and urinary health." },
      { name: "Male Infertility", description: "Andrology: Diagnosis and treatment of male reproductive disorders, including infertility and sexual dysfunction." },
      { name: "Urologic Oncology", description: "Diagnosis and treatment of cancers in the urinary system, including the bladder, kidneys, and prostate." },
      { name: "Renal Transplantation", description: "Surgical procedure involving the transplantation of a healthy kidney into a patient with kidney failure." },
      { name: "Endourology", description: "Minimally invasive surgical techniques for treating urinary tract and kidney conditions." },
      { name: "Neurourology", description: "Study and treatment of urinary disorders caused by neurological conditions." },
      { name: "Andrology", description: "Study and treatment of male reproductive system disorders and infertility." },
      { name: "Reconstructive Urology", description: "Surgical specialty focused on restoring form and function of the urinary tract." },
      { name: "Stone Disease", description: "Diagnosis and treatment of kidney stones and urinary tract stones." },
    ],
  },
];

const prisma = new PrismaClient();
async function seed() {
  for (const specialty of medicalSpecialties) {
    const { medicalsubspeciality, ...medicalSpecialtyData } = specialty;

    // Create the main MedicalSpecialty
    const createdMedicalSpecialty = await prisma.medicalSpeciality.create({
      data: medicalSpecialtyData,
    });

    // If medicalsubspeciality exists, create PsychiatrySubspecialties
    if (medicalsubspeciality && medicalsubspeciality.length > 0) {
      for (const subspecialty of medicalsubspeciality) {
        await prisma.medicalSubSpeciality.create({
          data: {
            ...subspecialty,
            medicalSpecialityId: createdMedicalSpecialty.id,
          },
        });
      }
    }
  }
}
try {
  await seed();
  await prisma.$disconnect();
} catch (e) {
  console.log(e);
  await prisma.$disconnect();
  process.exit(1);
}
